apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-app
  namespace: idp-ns
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: idp-ns
  path: ./apps/nginx
  prune: true
