apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-nginx
  namespace: idp-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-nginx-role
  namespace: idp-ns
rules:
- apiGroups: ["", "extensions", "apps", ""]
  resources: ["deployments", "services", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-nginx-binding
  namespace: idp-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-nginx-role
subjects:
- kind: ServiceAccount
  name: flux-nginx
  namespace: idp-ns
